# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: CI

on:
  push:
    paths:
      - "docs/**"
      - "scripts/**/*"
      - ".forgejo/workflows/**/*"

env:
  PHOENIX_CI: 1
  PHOENIX_CI_TYPE: "forgejo"
  PHOENIX_DEV_BRANCH: "dev"
  PHOENIX_FEDORA_VERSION: "44"
  PHOENIX_PROD_BRANCH: "pages"

jobs:
  lint:
    name: Lint
    runs-on: codeberg-medium
    container:
      image: fedora:${{ env.PHOENIX_FEDORA_VERSION }}
    steps:
      - name: Get dependencies
        run: |
          set -euo pipefail
          /bin/sudo /bin/dnf update -y --refresh
          /bin/sudo /bin/dnf install -y node

      - name: Checkout repo
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v7.0.1

      - name: Lint
        run: |
          set -euo pipefail
          /bin/sudo /bin/dnf update -y --refresh
          /bin/sudo /bin/dnf install -y bash curl shasum tar
          /bin/bash scripts/get_sources.sh shellcheck
          /bin/bash scripts/get_sources.sh shfmt
          /bin/bash scripts/lint.sh

  wiki:
    name: Wiki
    if: forgejo.ref_name == env.PHOENIX_DEV_BRANCH
    runs-on: codeberg-tiny-lazy
    container:
      image: fedora:${{ env.PHOENIX_FEDORA_VERSION }}
    steps:
      - name: Get dependencies
        run: |
          set -euo pipefail
          /bin/sudo /bin/dnf update -y --refresh
          /bin/sudo /bin/dnf install -y node

      - name: Checkout repo
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v7.0.1

      - name: Update wiki
        env:
          PHOENIX_FORGEJO_CI_API_TOKEN: ${{ secrets.PHOENIX_FORGEJO_CI_API_TOKEN }}
        run: |
          set -euo pipefail
          /bin/bash scripts/ci-update-wiki.sh

  build:
    name: Build
    needs: [lint]
    runs-on: codeberg-medium
    container:
      image: fedora:${{ env.PHOENIX_FEDORA_VERSION }}
    steps:
      - name: Get dependencies
        run: |
          set -euo pipefail
          /bin/sudo /bin/dnf update -y --refresh
          /bin/sudo /bin/dnf install -y node

      - name: Checkout repo
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v7.0.1

      - name: Build
        env:
          PHOENIX_CEL_ARTIFACTS_S3_ACCESS_KEY: ${{ secrets.PHOENIX_CEL_ARTIFACTS_S3_ACCESS_KEY }}
          PHOENIX_CEL_ARTIFACTS_S3_BUCKET_NAME: ${{ secrets.PHOENIX_CEL_ARTIFACTS_S3_BUCKET_NAME }}
          PHOENIX_CEL_ARTIFACTS_S3_ENDPOINT: ${{ secrets.PHOENIX_CEL_ARTIFACTS_S3_ENDPOINT }}
          PHOENIX_CEL_ARTIFACTS_S3_SECRET_KEY: ${{ secrets.PHOENIX_CEL_ARTIFACTS_S3_SECRET_KEY }}
        run: |
          set -euo pipefail
          /bin/bash scripts/ci-build.sh

  release:
    name: Release
    if: forgejo.ref_name == env.PHOENIX_PROD_BRANCH && forgejo.repository == 'celenity/Phoenix'
    needs: [build]
    runs-on: codeberg-medium
    container:
      image: fedora:${{ env.PHOENIX_FEDORA_VERSION }}
    steps:
      - name: Get dependencies
        run: |
          set -euo pipefail
          /bin/sudo /bin/dnf update -y --refresh
          /bin/sudo /bin/dnf install -y node

      - name: Checkout repo
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v7.0.1

      - name: Publish release
        env:
          PHOENIX_CEL_RELEASES_S3_ACCESS_KEY: ${{ secrets.PHOENIX_CEL_RELEASES_S3_ACCESS_KEY }}
          PHOENIX_CEL_RELEASES_S3_BUCKET_NAME: ${{ secrets.PHOENIX_CEL_RELEASES_S3_BUCKET_NAME }}
          PHOENIX_CEL_RELEASES_S3_ENDPOINT: ${{ secrets.PHOENIX_CEL_RELEASES_S3_ENDPOINT }}
          PHOENIX_CEL_RELEASES_S3_SECRET_KEY: ${{ secrets.PHOENIX_CEL_RELEASES_S3_SECRET_KEY }}
          PHOENIX_FORGEJO_CI_API_TOKEN: ${{ secrets.PHOENIX_FORGEJO_CI_API_TOKEN }}
          PHOENIX_GITHUB_CI_API_TOKEN: ${{ secrets.PHOENIX_GITHUB_CI_API_TOKEN }}
          PHOENIX_GITLAB_CI_API_TOKEN: ${{ secrets.PHOENIX_GITLAB_CI_API_TOKEN }}
        run: |
          set -euo pipefail
          /bin/bash scripts/ci-publish-release.sh
