# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Docs

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'docs/**'

env:
  REPO: ${{ forgejo.repository }}
  USER: 'Wiki Author'
  EMAIL: 'wiki_author@noreply.codeberg.org'
  URL: 'codeberg.org'

jobs:
  generate-wiki:
    runs-on: codeberg-tiny-lazy
    steps:
      - name: Checkout repo
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v7.0.1

      - name: Pull wiki
        env:
          PHOENIX_FORGEJO_CI_API_TOKEN: ${{ secrets.PHOENIX_FORGEJO_CI_API_TOKEN }}
        run: |
          set -euo pipefail
          mkdir wikidir
          cd wikidir
          git config --global user.name ${{ env.USER }}
          git config --global user.email ${{ env.EMAIL }}
          git init -b 'main'
          set +x
          git pull https://${{ env.PHOENIX_FORGEJO_CI_API_TOKEN }}@${{ env.URL }}/${{ env.REPO }}.wiki.git

      - name: Push content
        env:
          PHOENIX_FORGEJO_CI_API_TOKEN: ${{ secrets.PHOENIX_FORGEJO_CI_API_TOKEN }}
        run: |
          set -euo pipefail
          apt-get update
          apt-get install -y rsync
          rsync -av --delete docs/ wikidir/ --exclude .git
          cd wikidir/
          git add .
          git commit -m 'Update wiki'
          set +x
          git push -f --set-upstream https://${{ env.PHOENIX_FORGEJO_CI_API_TOKEN }}@${{ env.URL }}/${{ env.REPO }}.wiki.git main
