name: Web Compat
description: For reporting breakage or unexpected/unintended behavior with specific websites.
title: "[WEB COMPAT] PLEASE REPLACE THIS TEXT WITH A SUMMARY OF YOUR ISSUE"
labels: ["web compat"]
assignees:
  - celenity
  - celenityy
body:
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: Please confirm that you have already checked the Website Compatibility wiki page (https://phoenix.celenity.dev/compat), and that this issue is NOT currently listed.
          required: true

  - type: textarea
    id: version
    attributes:
      label: What version of Phoenix are you using?
      description: |
        An easy way to tell is by checking the value of `browser.phoenix.version` in your `about:config`.
    validations:
      required: true

  - type: textarea
    id: browser
    attributes:
      label: What version of Firefox are you using with Phoenix?
      description: |
        An easy way to tell is by checking the value besides `Version` on `about:support`.
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: What operating system are you experiencing this issue on?
      description: |
        If your operating system is not listed, please select `Other` and enter its name in the comment field below. **Note that operating systems other than what's listed below are only supported on a best case basis.**
      multiple: true
      options:
        - Android
        - Arch Linux
        - Debian
        - Fedora Linux
        - macOS
        - Ubuntu
        - Other
    validations:
      required: true
  - type: input
    id: other
    attributes:
      label: Other
    validations:
      required: true
