# Phoenix common environment variables

## CAUTION: Do NOT source this directly!
## Source 'env.sh' instead.

## Additionally, if you need to override any variables here, export them to your shell manually or use `env_override.sh`.
## Do NOT edit this file directly.

# If variables are defined with a custom `env_override.sh` file (located at the root project directory), let's use those
## These need to be set first, to ensure that they don't interfere with certain variables
readonly PHOENIX_ENV_OVERRIDE="${PHOENIX_ROOT}/env_override.sh"
if [[ -f "${PHOENIX_ENV_OVERRIDE}" ]]; then
  source "${PHOENIX_ENV_OVERRIDE}"
fi

# Phoenix

# Scripts directory
readonly PHOENIX_SCRIPTS="${PHOENIX_ROOT}/scripts"
export PHOENIX_SCRIPTS

## Phoenix utilities
readonly PHOENIX_UTILS="${PHOENIX_SCRIPTS}/utilities.sh"
export PHOENIX_UTILS

# Set our platform, OS, and architecture
readonly PHOENIX_ENV_HELPERS="${PHOENIX_SCRIPTS}/env_helpers.sh"
export PHOENIX_ENV_HELPERS
source "${PHOENIX_ENV_HELPERS}"

# Whether we're being invoked from a Nix flake
readonly PHOENIX_NIX_DEFAULT=0
if [[ -z "${PHOENIX_NIX+x}" ]]; then
  PHOENIX_NIX="${PHOENIX_NIX_DEFAULT}"
fi
readonly PHOENIX_NIX
export PHOENIX_NIX

# Version info
readonly PHOENIX_VERSIONS="${PHOENIX_SCRIPTS}/versions.sh"
export PHOENIX_VERSIONS

# Archives directory
readonly PHOENIX_ARCHIVES="${PHOENIX_ROOT}/archives"
export PHOENIX_ARCHIVES

# Build directory
readonly PHOENIX_BUILD_DEFAULT="${PHOENIX_ROOT}/build"
if [[ -z "${PHOENIX_BUILD+x}" ]]; then
  if [ "${PHOENIX_NIX}" == 1 ]; then
    # Nix needs to use /tmp here, see https://codeberg.org/celenity/Dove/issues/59
    PHOENIX_BUILD='/tmp/phoenix/build'
  else
    PHOENIX_BUILD="${PHOENIX_BUILD_DEFAULT}"
  fi
fi
readonly PHOENIX_BUILD
export PHOENIX_BUILD

# External sources directory
readonly PHOENIX_EXTERNAL="${PHOENIX_ROOT}/external"
export PHOENIX_EXTERNAL

# External downloads/resources directory
readonly PHOENIX_DOWNLOADS="${PHOENIX_EXTERNAL}/downloads"
export PHOENIX_DOWNLOADS

# Temporary build directory
readonly PHOENIX_TEMP="${PHOENIX_BUILD}/tmp"
export PHOENIX_TEMP

# Build resources directory
readonly PHOENIX_BUILD_RESOURCES="${PHOENIX_ROOT}/build-resources"
export PHOENIX_BUILD_RESOURCES

# Specialized config directory
readonly PHOENIX_SPECS="${PHOENIX_ROOT}/specs"
export PHOENIX_SPECS

# Phoenix outputs directory
readonly PHOENIX_OUTPUTS_DEFAULT="${PHOENIX_ROOT}/outputs"
if [[ -z "${PHOENIX_OUTPUTS+x}" ]]; then
  PHOENIX_OUTPUTS="${PHOENIX_OUTPUTS_DEFAULT}"
fi
readonly PHOENIX_OUTPUTS
export PHOENIX_OUTPUTS

# Android outputs directory
readonly PHOENIX_ANDROID_OUTPUTS="${PHOENIX_OUTPUTS}/android"
export PHOENIX_ANDROID_OUTPUTS

# Linux outputs directory
readonly PHOENIX_LINUX_OUTPUTS="${PHOENIX_OUTPUTS}/linux"
export PHOENIX_LINUX_OUTPUTS

## Linux (Flatpak) outputs directory
readonly PHOENIX_LINUX_FLATPAK_OUTPUTS="${PHOENIX_OUTPUTS}/linux-flatpak"
export PHOENIX_LINUX_FLATPAK_OUTPUTS

# OS X outputs directory
readonly PHOENIX_OSX_OUTPUTS="${PHOENIX_OUTPUTS}/osx"
export PHOENIX_OSX_OUTPUTS

## OS X (Intel) outputs directory
readonly PHOENIX_OSX_INTEL_OUTPUTS="${PHOENIX_OUTPUTS}/osx-intel"
export PHOENIX_OSX_INTEL_OUTPUTS

# Windows outputs directory
readonly PHOENIX_WINDOWS_OUTPUTS="${PHOENIX_OUTPUTS}/windows"
export PHOENIX_WINDOWS_OUTPUTS

# Should we create a log file for build.sh? (Default)
readonly PHOENIX_LOG_BUILD_DEFAULT=1
if [[ -z "${PHOENIX_LOG_BUILD+x}" ]]; then
  PHOENIX_LOG_BUILD="${PHOENIX_LOG_BUILD_DEFAULT}"
fi
readonly PHOENIX_LOG_BUILD
export PHOENIX_LOG_BUILD

# Should we create a log file for get_sources.sh? (Default)
readonly PHOENIX_LOG_SOURCES_DEFAULT=1
if [[ -z "${PHOENIX_LOG_SOURCES+x}" ]]; then
  PHOENIX_LOG_SOURCES="${PHOENIX_LOG_SOURCES_DEFAULT}"
fi
readonly PHOENIX_LOG_SOURCES
export PHOENIX_LOG_SOURCES

# Directory where we should store log files (if logging is desired)
readonly PHOENIX_LOG_DIR_DEFAULT="${PHOENIX_BUILD}/logs"
if [[ -z "${PHOENIX_LOG_DIR+x}" ]]; then
  PHOENIX_LOG_DIR="${PHOENIX_LOG_DIR_DEFAULT}"
fi
readonly PHOENIX_LOG_DIR
export PHOENIX_LOG_DIR

# GNU awk
if [[ "${PHOENIX_OS}" == 'osx' ]]; then
  readonly PHOENIX_AWK_DEFAULT='gawk'
else
  readonly PHOENIX_AWK_DEFAULT='awk'
fi
if [[ -z "${PHOENIX_AWK+x}" ]]; then
  PHOENIX_AWK="${PHOENIX_AWK_DEFAULT}"
fi
readonly PHOENIX_AWK
export PHOENIX_AWK

# GNU sed
if [[ "${PHOENIX_OS}" == 'osx' ]]; then
  readonly PHOENIX_SED_DEFAULT='gsed'
else
  readonly PHOENIX_SED_DEFAULT='sed'
fi
if [[ -z "${PHOENIX_SED+x}" ]]; then
  PHOENIX_SED="${PHOENIX_SED_DEFAULT}"
fi
readonly PHOENIX_SED
export PHOENIX_SED

# GNU tar
if [[ "${PHOENIX_OS}" == 'osx' ]]; then
  readonly PHOENIX_TAR_DEFAULT='gtar'
else
  readonly PHOENIX_TAR_DEFAULT='tar'
fi
if [[ -z "${PHOENIX_TAR+x}" ]]; then
  PHOENIX_TAR="${PHOENIX_TAR_DEFAULT}"
fi
readonly PHOENIX_TAR
export PHOENIX_TAR

# Python
readonly PHOENIX_PYTHON_DIR_DEFAULT="${PHOENIX_EXTERNAL}/python"
if [[ -z "${PHOENIX_PYTHON_DIR+x}" ]]; then
  PHOENIX_PYTHON_DIR="${PHOENIX_PYTHON_DIR_DEFAULT}"
fi
readonly PHOENIX_PYTHON_DIR
export PHOENIX_PYTHON_DIR

# Python (UV) environment
readonly PHOENIX_PYENV_DIR_DEFAULT="${PHOENIX_BUILD}/pyenv"
if [[ -z "${PHOENIX_PYENV_DIR+x}" ]]; then
  PHOENIX_PYENV_DIR="${PHOENIX_PYENV_DIR_DEFAULT}"
fi
readonly PHOENIX_PYENV_DIR
readonly PHOENIX_PYENV="${PHOENIX_PYENV_DIR}/bin/activate"
export PHOENIX_PYENV
export PHOENIX_PYENV_DIR

if [[ "${PHOENIX_NIX}" == 1 ]]; then
  ## Nix doesn't want/need to set a specific Python path, see discussion at https://codeberg.org/celenity/Dove/issues/59
  ## and https://codeberg.org/celenity/Phoenix/issues/252
  readonly PHOENIX_PYTHON_DEFAULT='python'
else
  readonly PHOENIX_PYTHON_DEFAULT="${PHOENIX_PYENV_DIR}/bin/python"
fi
if [[ -z "${PHOENIX_PYTHON+x}" ]]; then
  PHOENIX_PYTHON="${PHOENIX_PYTHON_DEFAULT}"
fi
readonly PHOENIX_PYTHON
export PHOENIX_PYTHON

# UV
readonly PHOENIX_UV_DIR_DEFAULT="${PHOENIX_EXTERNAL}/uv"
if [[ -z "${PHOENIX_UV_DIR+x}" ]]; then
  PHOENIX_UV_DIR="${PHOENIX_UV_DIR_DEFAULT}"
fi
readonly PHOENIX_UV_DIR
readonly PHOENIX_UV="${PHOENIX_UV_DIR}/uv"
export PHOENIX_UV
export PHOENIX_UV_DIR

# UV (local directory)
readonly PHOENIX_UV_LOCAL_DEFAULT="${PHOENIX_BUILD}/uv"
if [[ -z "${PHOENIX_UV_LOCAL+x}" ]]; then
  PHOENIX_UV_LOCAL="${PHOENIX_UV_LOCAL_DEFAULT}"
fi
readonly PHOENIX_UV_LOCAL
export PHOENIX_UV_LOCAL

# UV cache
readonly PHOENIX_UV_CACHE_DEFAULT="${PHOENIX_UV_LOCAL}/cache"
if [[ -z "${PHOENIX_UV_CACHE+x}" ]]; then
  PHOENIX_UV_CACHE="${PHOENIX_UV_CACHE_DEFAULT}"
fi
readonly PHOENIX_UV_CACHE
export PHOENIX_UV_CACHE

# UV Python directory
readonly PHOENIX_UV_PYTHON_DEFAULT="${PHOENIX_UV_LOCAL}/python"
if [[ -z "${PHOENIX_UV_PYTHON+x}" ]]; then
  PHOENIX_UV_PYTHON="${PHOENIX_UV_PYTHON_DEFAULT}"
fi
readonly PHOENIX_UV_PYTHON
export PHOENIX_UV_PYTHON

# UV tools
readonly PHOENIX_UV_TOOLS_DEFAULT="${PHOENIX_UV_LOCAL}/tools"
if [[ -z "${PHOENIX_UV_TOOLS+x}" ]]; then
  PHOENIX_UV_TOOLS="${PHOENIX_UV_TOOLS_DEFAULT}"
fi
readonly PHOENIX_UV_TOOLS
export PHOENIX_UV_TOOLS

# Cipher suites
## (This enforces strong cipher suites - see ex. https://browserleaks.com/tls)
readonly PHOENIX_CIPHERS_DEFAULT='TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384'
if [[ -z "${PHOENIX_CIPHERS+x}" ]]; then
  PHOENIX_CIPHERS="${PHOENIX_CIPHERS_DEFAULT}"
fi
readonly PHOENIX_CIPHERS
export PHOENIX_CIPHERS

# If curl flags are added, this determines whether they should be appended to our default flags (default),
## or if they should override them entirely
readonly PHOENIX_CURL_FLAGS_OVERRIDE_DEFAULT=0
if [[ -z "${PHOENIX_CURL_FLAGS_OVERRIDE+x}" ]]; then
  PHOENIX_CURL_FLAGS_OVERRIDE="${PHOENIX_CURL_FLAGS_OVERRIDE_DEFAULT}"
fi
readonly PHOENIX_CURL_FLAGS_OVERRIDE
export PHOENIX_CURL_FLAGS_OVERRIDE

# curl flags
readonly PHOENIX_CURL_FLAGS_DEFAULT="-q --disable --no-netrc -j -e "" -A "" -S --ciphers ${PHOENIX_CIPHERS} --clobber --create-dirs --delegation none --disallow-username-in-url --doh-cert-status --ftp-create-dirs --ftp-ssl-control --junk-session-cookies --no-basic --no-ca-native --no-digest --no-doh-insecure --no-http0.9 --no-insecure --no-proxy-insecure --no-negotiate --no-ntlm --no-proxy-basic --no-proxy-ca-native --no-proxy-digest --no-proxy-insecure --no-proxy-ssl-allow-beast --no-proxy-ssl-auto-client-cert --no-sessionid --no-skip-existing --no-ssl --no-ssl-allow-beast --no-ssl-auto-client-cert --no-ssl-no-revoke --no-ssl-revoke-best-effort --no-tls-earlydata --no-xattr --progress-meter --proto -all,https --proto-default https --proto-redir -all,https --referer "" --remove-on-error --show-error --ssl-reqd --tlsv1.2 --trace-time --user-agent "" --verbose"
if [[ -z "${PHOENIX_CURL_FLAGS+x}" ]]; then
  readonly PHOENIX_CURL_FLAGS="${PHOENIX_CURL_FLAGS_DEFAULT}"
elif [[ "${PHOENIX_CURL_FLAGS_OVERRIDE}" == 1 ]]; then
  readonly PHOENIX_CURL_FLAGS="${PHOENIX_CURL_FLAGS}"
else
  readonly PHOENIX_CURL_FLAGS="${PHOENIX_CURL_FLAGS_DEFAULT} ${PHOENIX_CURL_FLAGS}"
fi
export PHOENIX_CURL_FLAGS

# Whether we're ONLY building Phoenix for Android
readonly PHOENIX_ANDROID_ONLY_DEFAULT=0
if [[ -z "${PHOENIX_ANDROID_ONLY+x}" ]]; then
  PHOENIX_ANDROID_ONLY="${PHOENIX_ANDROID_ONLY_DEFAULT}"
fi
readonly PHOENIX_ANDROID_ONLY
export PHOENIX_ANDROID_ONLY
if [ "${PHOENIX_ANDROID_ONLY}" == 1 ]; then
  PHOENIX_ANDROID=1
  PHOENIX_LINUX=0
  PHOENIX_LINUX_FLATPAK=0
  PHOENIX_OSX=0
  PHOENIX_OSX_INTEL=0
  PHOENIX_WINDOWS=0
fi

# Whether we're ONLY building Phoenix for Linux
readonly PHOENIX_LINUX_ONLY_DEFAULT=0
if [ "${PHOENIX_NIX}" == 1 ] && [ "${PHOENIX_OS}" != 'osx' ]; then
  # Nix flakes should only build their respective platform
  PHOENIX_LINUX_ONLY=1
elif [[ -z "${PHOENIX_LINUX_ONLY+x}" ]]; then
  PHOENIX_LINUX_ONLY="${PHOENIX_LINUX_ONLY_DEFAULT}"
fi
readonly PHOENIX_LINUX_ONLY
export PHOENIX_LINUX_ONLY
if [ "${PHOENIX_LINUX_ONLY}" == 1 ]; then
  PHOENIX_LINUX=1
  PHOENIX_ANDROID=0
  PHOENIX_LINUX_FLATPAK=0
  PHOENIX_OSX=0
  PHOENIX_OSX_INTEL=0
  PHOENIX_WINDOWS=0
fi

# Whether we're ONLY building Phoenix for Linux (Flatpak)
readonly PHOENIX_LINUX_FLATPAK_ONLY_DEFAULT=0
if [[ -z "${PHOENIX_LINUX_FLATPAK_ONLY+x}" ]]; then
  PHOENIX_LINUX_FLATPAK_ONLY="${PHOENIX_LINUX_FLATPAK_ONLY_DEFAULT}"
fi
readonly PHOENIX_LINUX_FLATPAK_ONLY
export PHOENIX_LINUX_FLATPAK_ONLY
if [ "${PHOENIX_LINUX_FLATPAK_ONLY}" == 1 ]; then
  PHOENIX_LINUX_FLATPAK=1
  PHOENIX_ANDROID=0
  PHOENIX_LINUX=0
  PHOENIX_OSX=0
  PHOENIX_OSX_INTEL=0
  PHOENIX_WINDOWS=0
fi

# Whether we're ONLY building Phoenix for OS X
readonly PHOENIX_OSX_ONLY_DEFAULT=0
if [ "${PHOENIX_NIX}" == 1 ] && [ "${PHOENIX_OS}" == 'osx' ]; then
  # Nix flakes should only build their respective platform
  PHOENIX_OSX_ONLY=1
elif [[ -z "${PHOENIX_OSX_ONLY+x}" ]]; then
  PHOENIX_OSX_ONLY="${PHOENIX_OSX_ONLY_DEFAULT}"
fi
readonly PHOENIX_OSX_ONLY
export PHOENIX_OSX_ONLY
if [ "${PHOENIX_OSX_ONLY}" == 1 ]; then
  PHOENIX_OSX=1
  PHOENIX_ANDROID=0
  PHOENIX_LINUX=0
  PHOENIX_LINUX_FLATPAK=0
  PHOENIX_OSX_INTEL=0
  PHOENIX_WINDOWS=0
fi

# Whether we're ONLY building Phoenix for OS X (Intel)
readonly PHOENIX_OSX_INTEL_ONLY_DEFAULT=0
if [[ -z "${PHOENIX_OSX_INTEL_ONLY+x}" ]]; then
  PHOENIX_OSX_INTEL_ONLY="${PHOENIX_OSX_INTEL_ONLY_DEFAULT}"
fi
readonly PHOENIX_OSX_INTEL_ONLY
export PHOENIX_OSX_INTEL_ONLY
if [ "${PHOENIX_OSX_INTEL_ONLY}" == 1 ]; then
  PHOENIX_OSX_INTEL=1
  PHOENIX_ANDROID=0
  PHOENIX_LINUX=0
  PHOENIX_LINUX_FLATPAK=0
  PHOENIX_OSX=0
  PHOENIX_WINDOWS=0
fi

# Whether we're ONLY building Phoenix for Windows
readonly PHOENIX_WINDOWS_ONLY_DEFAULT=0
if [[ -z "${PHOENIX_WINDOWS_ONLY+x}" ]]; then
  PHOENIX_WINDOWS_ONLY="${PHOENIX_WINDOWS_ONLY_DEFAULT}"
fi
readonly PHOENIX_WINDOWS_ONLY
export PHOENIX_WINDOWS_ONLY
if [ "${PHOENIX_WINDOWS_ONLY}" == 1 ]; then
  PHOENIX_WINDOWS=1
  PHOENIX_ANDROID=0
  PHOENIX_LINUX=0
  PHOENIX_LINUX_FLATPAK=0
  PHOENIX_OSX=0
  PHOENIX_OSX_INTEL=0
fi

# Whether we're building Phoenix for Android (Default)
readonly PHOENIX_ANDROID_DEFAULT=1
if [ "${PHOENIX_NIX}" == 1 ]; then
  # This makes absolutely no sense for Nix - ensure we never try to build Android there
  PHOENIX_ANDROID=0
elif [[ -z "${PHOENIX_ANDROID+x}" ]]; then
  PHOENIX_ANDROID="${PHOENIX_ANDROID_DEFAULT}"
fi
readonly PHOENIX_ANDROID
export PHOENIX_ANDROID

# Whether we're building Phoenix for Linux (Default)
readonly PHOENIX_LINUX_DEFAULT=1
if [[ -z "${PHOENIX_LINUX+x}" ]]; then
  PHOENIX_LINUX="${PHOENIX_LINUX_DEFAULT}"
fi
readonly PHOENIX_LINUX
export PHOENIX_LINUX

# Whether we're building Phoenix for Linux (Flatpak) (Default)
readonly PHOENIX_LINUX_FLATPAK_DEFAULT=1
if [[ -z "${PHOENIX_LINUX_FLATPAK+x}" ]]; then
  PHOENIX_LINUX_FLATPAK="${PHOENIX_LINUX_FLATPAK_DEFAULT}"
fi
readonly PHOENIX_LINUX_FLATPAK
export PHOENIX_LINUX_FLATPAK

# Whether we're building Phoenix for OS X (Default)
readonly PHOENIX_OSX_DEFAULT=1
if [[ -z "${PHOENIX_OSX+x}" ]]; then
  PHOENIX_OSX="${PHOENIX_OSX_DEFAULT}"
fi
readonly PHOENIX_OSX
export PHOENIX_OSX

# Whether we're building Phoenix for OS X (Intel) (Default)
readonly PHOENIX_OSX_INTEL_DEFAULT=1
if [[ -z "${PHOENIX_OSX_INTEL+x}" ]]; then
  PHOENIX_OSX_INTEL="${PHOENIX_OSX_INTEL_DEFAULT}"
fi
readonly PHOENIX_OSX_INTEL
export PHOENIX_OSX_INTEL

# Whether we're building Phoenix for Windows (Default)
readonly PHOENIX_WINDOWS_DEFAULT=1
if [ "${PHOENIX_NIX}" == 1 ]; then
  # This makes absolutely no sense for Nix - ensure we never try to build Windows there
  PHOENIX_WINDOWS=0
elif [[ -z "${PHOENIX_WINDOWS+x}" ]]; then
  PHOENIX_WINDOWS="${PHOENIX_WINDOWS_DEFAULT}"
fi
readonly PHOENIX_WINDOWS
export PHOENIX_WINDOWS

# Whether we should allow users to control whether Remote Debugging (`devtools.debugger.remote-enabled`) is reset per-session via a preference
## If PHOENIX_FORCE_RESET_REMOTE_DEBUGGING is set to 1 (Default), `devtools.debugger.remote-enabled` is ALWAYS reset per-session
## If PHOENIX_FORCE_RESET_REMOTE_DEBUGGING is set to 0, `devtools.debugger.remote-enabled` is only reset per-session if
## `browser.phoenix.reset.devtools.debugger.remote-enabled` is set to `true`
## (Useful because some like IronFox handle this with their own mechanisms instead)
readonly PHOENIX_FORCE_RESET_REMOTE_DEBUGGING_DEFAULT=1
if [[ -z "${PHOENIX_FORCE_RESET_REMOTE_DEBUGGING+x}" ]]; then
    PHOENIX_FORCE_RESET_REMOTE_DEBUGGING="${PHOENIX_FORCE_RESET_REMOTE_DEBUGGING_DEFAULT}"
fi
readonly PHOENIX_FORCE_RESET_REMOTE_DEBUGGING
export PHOENIX_FORCE_RESET_REMOTE_DEBUGGING

# Whether we should build enterprise policies for Android
## This is usually not supported/possible to apply on Android, but some (ex. IronFox) do patch/add support to apply them
readonly PHOENIX_ANDROID_POLICIES_DEFAULT=0
if [[ -z "${PHOENIX_ANDROID_POLICIES+x}" ]]; then
  PHOENIX_ANDROID_POLICIES="${PHOENIX_ANDROID_POLICIES_DEFAULT}"
fi
readonly PHOENIX_ANDROID_POLICIES
export PHOENIX_ANDROID_POLICIES

# Whether we should build Phoenix for desktop (non-Android) platforms in the static .js prefs format
## This is not recommended in favor of the .cfg format, and will likely be removed entirely in the near future
readonly PHOENIX_STATIC_JS_DEFAULT=0
if [[ -z "${PHOENIX_STATIC_JS+x}" ]]; then
  PHOENIX_STATIC_JS="${PHOENIX_STATIC_JS_DEFAULT}"
fi
readonly PHOENIX_STATIC_JS
export PHOENIX_STATIC_JS

# Whether we should build Phoenix for Android in the static .js prefs format
## This is the default for Android because its typically the only supported mechanism for applying prefs there
## But some (ex. IronFox) do patch/add support for using Phoenix in the .cfg format, so they may not want/need the static .js format
readonly PHOENIX_STATIC_JS_ANDROID_DEFAULT=1
if [[ -z "${PHOENIX_STATIC_JS_ANDROID+x}" ]]; then
  PHOENIX_STATIC_JS_ANDROID="${PHOENIX_STATIC_JS_ANDROID_DEFAULT}"
fi
readonly PHOENIX_STATIC_JS_ANDROID
export PHOENIX_STATIC_JS_ANDROID

# Whether we should exclude "NO-MAIL" preferences when building Phoenix
## (ex. for Dove)
readonly PHOENIX_MAIL_DEFAULT=0
if [[ -z "${PHOENIX_MAIL+x}" ]]; then
  PHOENIX_MAIL="${PHOENIX_MAIL_DEFAULT}"
fi
readonly PHOENIX_MAIL
export PHOENIX_MAIL

# Whether we should use Phoenix Extended
## When this is enabled:
### For Phoenix in the .cfg format, the pref to enable Phoenix Extended is true by default
### For Phoenix in the .js format, the pref files are parsed to include preferences/values for
#### Phoenix Extended at build-time
readonly PHOENIX_EXTENDED_DEFAULT=1
if [ "${PHOENIX_MAIL}" == 1 ]; then
  # Mail always uses Extended
  PHOENIX_EXTENDED=1
elif [[ -z "${PHOENIX_EXTENDED+x}" ]]; then
  PHOENIX_EXTENDED="${PHOENIX_EXTENDED_DEFAULT}"
fi
readonly PHOENIX_EXTENDED
export PHOENIX_EXTENDED

# Whether we should support Phoenix's specialized config functionality
readonly PHOENIX_NO_SPEC_DEFAULT=0
if [ "${PHOENIX_ANDROID_ONLY}" == 1 ] || [ "${PHOENIX_MAIL}" == 1 ]; then
  # Android and Mail never want or need specialized configs
  PHOENIX_NO_SPEC=1
elif [[ -z "${PHOENIX_NO_SPEC+x}" ]]; then
  PHOENIX_NO_SPEC="${PHOENIX_NO_SPEC_DEFAULT}"
fi
readonly PHOENIX_NO_SPEC
export PHOENIX_NO_SPEC

# Where a .cfg file containing overrides for Phoenix-specific preferences is located
## This is separate from the standard overrides file because these preferences must be set early in order to take effect
## May have other use cases as well
readonly PHOENIX_OVERRIDES_CFG_DEFAULT='undefined'
if [ -z "${PHOENIX_OVERRIDES_CFG+x}" ]; then
    PHOENIX_OVERRIDES_CFG="${PHOENIX_OVERRIDES_CFG_DEFAULT}"
fi
readonly PHOENIX_OVERRIDES_CFG
export PHOENIX_OVERRIDES_CFG

# Where an additional .cfg file is located that should be appended to phoenix.cfg
## Meant for downstream projects (ex. Dove, IronFox, LibreWolf) to simplify the process of overriding/setting additional preferences
## (ex. for overriding preferences that are not Phoenix-specific)
readonly PHOENIX_EXTRA_CFG_DEFAULT='undefined'
if [ -z "${PHOENIX_EXTRA_CFG+x}" ]; then
  PHOENIX_EXTRA_CFG="${PHOENIX_EXTRA_CFG_DEFAULT}"
fi
readonly PHOENIX_EXTRA_CFG
export PHOENIX_EXTRA_CFG

# Where an additional .js file is located that should be appended to phoenix.cfg
## Meant for downstream projects (ex. Dove, IronFox, LibreWolf) to simplify the process of overriding/setting additional preferences
readonly PHOENIX_EXTRA_JS_DEFAULT='undefined'
if [ -z "${PHOENIX_EXTRA_JS+x}" ]; then
  PHOENIX_EXTRA_JS="${PHOENIX_EXTRA_JS_DEFAULT}"
fi
readonly PHOENIX_EXTRA_JS
export PHOENIX_EXTRA_JS

# Where an additional policies.json file is located that should be applied to all platforms
## Meant for downstream projects (ex. Dove, IronFox, LibreWolf) to simplify the process of overriding/setting additional policies
readonly PHOENIX_EXTRA_POLICIES_DEFAULT='undefined'
if [ -z "${PHOENIX_EXTRA_POLICIES+x}" ]; then
  PHOENIX_EXTRA_POLICIES="${PHOENIX_EXTRA_POLICIES_DEFAULT}"
fi
readonly PHOENIX_EXTRA_POLICIES
export PHOENIX_EXTRA_POLICIES

# Where an additional policies.json file is located that should ONLY be applied to Android
readonly PHOENIX_EXTRA_POLICIES_ANDROID_DEFAULT='undefined'
if [ -z "${PHOENIX_EXTRA_POLICIES_ANDROID+x}" ]; then
  PHOENIX_EXTRA_POLICIES_ANDROID="${PHOENIX_EXTRA_POLICIES_ANDROID_DEFAULT}"
fi
readonly PHOENIX_EXTRA_POLICIES_ANDROID
export PHOENIX_EXTRA_POLICIES_ANDROID

# Where an additional policies.json file is located that should ONLY be applied to Linux
readonly PHOENIX_EXTRA_POLICIES_LINUX_DEFAULT='undefined'
if [ -z "${PHOENIX_EXTRA_POLICIES_LINUX+x}" ]; then
  PHOENIX_EXTRA_POLICIES_LINUX="${PHOENIX_EXTRA_POLICIES_LINUX_DEFAULT}"
fi
readonly PHOENIX_EXTRA_POLICIES_LINUX
export PHOENIX_EXTRA_POLICIES_LINUX

# Where an additional policies.json file is located that should ONLY be applied to Linux (non-Flatpak)
readonly PHOENIX_EXTRA_POLICIES_LINUX_NONFLATPAK_DEFAULT='undefined'
if [ -z "${PHOENIX_EXTRA_POLICIES_LINUX_NONFLATPAK+x}" ]; then
  PHOENIX_EXTRA_POLICIES_LINUX_NONFLATPAK="${PHOENIX_EXTRA_POLICIES_LINUX_NONFLATPAK_DEFAULT}"
fi
readonly PHOENIX_EXTRA_POLICIES_LINUX_NONFLATPAK
export PHOENIX_EXTRA_POLICIES_LINUX_NONFLATPAK

# Where an additional policies.json file is located that should ONLY be applied to Linux (Flatpak)
readonly PHOENIX_EXTRA_POLICIES_LINUX_FLATPAK_DEFAULT='undefined'
if [ -z "${PHOENIX_EXTRA_POLICIES_LINUX_FLATPAK+x}" ]; then
  PHOENIX_EXTRA_POLICIES_LINUX_FLATPAK="${PHOENIX_EXTRA_POLICIES_LINUX_FLATPAK_DEFAULT}"
fi
readonly PHOENIX_EXTRA_POLICIES_LINUX_FLATPAK
export PHOENIX_EXTRA_POLICIES_LINUX_FLATPAK

# Where an additional policies.json file is located that should ONLY be applied to OS X
readonly PHOENIX_EXTRA_POLICIES_OSX_DEFAULT='undefined'
if [ -z "${PHOENIX_EXTRA_POLICIES_OSX+x}" ]; then
  PHOENIX_EXTRA_POLICIES_OSX="${PHOENIX_EXTRA_POLICIES_OSX_DEFAULT}"
fi
readonly PHOENIX_EXTRA_POLICIES_OSX
export PHOENIX_EXTRA_POLICIES_OSX

# Where an additional policies.json file is located that should ONLY be applied to OS X (Apple Silicon)
readonly PHOENIX_EXTRA_POLICIES_OSX_SILICON_DEFAULT='undefined'
if [ -z "${PHOENIX_EXTRA_POLICIES_OSX_SILICON+x}" ]; then
  PHOENIX_EXTRA_POLICIES_OSX_SILICON="${PHOENIX_EXTRA_POLICIES_OSX_SILICON_DEFAULT}"
fi
readonly PHOENIX_EXTRA_POLICIES_OSX_SILICON
export PHOENIX_EXTRA_POLICIES_OSX_SILICON

# Where an additional policies.json file is located that should ONLY be applied to OS X (Intel)
readonly PHOENIX_EXTRA_POLICIES_OSX_INTEL_DEFAULT='undefined'
if [ -z "${PHOENIX_EXTRA_POLICIES_OSX_INTEL+x}" ]; then
  PHOENIX_EXTRA_POLICIES_OSX_INTEL="${PHOENIX_EXTRA_POLICIES_OSX_INTEL_DEFAULT}"
fi
readonly PHOENIX_EXTRA_POLICIES_OSX_INTEL
export PHOENIX_EXTRA_POLICIES_OSX_INTEL

# Where an additional policies.json file is located that should ONLY be applied to Windows
readonly PHOENIX_EXTRA_POLICIES_WINDOWS_DEFAULT='undefined'
if [ -z "${PHOENIX_EXTRA_POLICIES_WINDOWS+x}" ]; then
  PHOENIX_EXTRA_POLICIES_WINDOWS="${PHOENIX_EXTRA_POLICIES_WINDOWS_DEFAULT}"
fi
readonly PHOENIX_EXTRA_POLICIES_WINDOWS
export PHOENIX_EXTRA_POLICIES_WINDOWS

# Set our external environment variables
readonly PHOENIX_ENV_EXTERNAL="${PHOENIX_SCRIPTS}/env_external.sh"
source "${PHOENIX_ENV_EXTERNAL}"

# We've now set our environment variables...
readonly PHOENIX_SET_ENVS=1
export PHOENIX_SET_ENVS
